### ISSUE TITLE
Typescript Support?

### ISSUE THREAD

**Issue by diragb** [deanilvincent/check-password-strength#23]
![Not+anime+big+hero+6+the+_136142c1335c1e6049a8d64b0f481f7c](https://user-images.githubusercontent.com/36959928/93003261-dd7c6400-f55a-11ea-8013-a2080813710b.jpg)

great package!
are you considering adding type support to your package?

**Comment by deanilvincent** [comment]
Hello @diragb 
You can use ES6 import for typescript file. Like this: 
```
import passwordStrength from 'check-password-strength'
...
const strength = passwordStrength(password)
```
See updated file for demo [here](https://github.com/deanilvincent/check-password-strength-demo/blob/master/app/src/app/app.component.ts)

I hope this helps :)
