### ISSUE TITLE
Make the lib configurable

### ISSUE THREAD

**Issue by Ennoriel** [deanilvincent/check-password-strength#28]
Hello!

Your library does a great job!

I would be glad to make a PR to make it configurable, say with a parameter
```
[
  {
     id: 0,
     value: 'Weak',
     requires: ['lowercase', 'uppercase']
     length: 5
  },...
]
```

It would be retrocompatible with a default parameter set as the actual configuration.

What do you think?

**Comment by deanilvincent** [comment]
Hi @Ennoriel 

Thanks for the feedback. I think that's a good a suggestion. Sure, you can contribute a PR feature/option for that. :) Stay safe!

**Comment by Ennoriel** [comment]
Hi @deanilvincent

You can check my commit [here](https://github.com/Ennoriel/check-password-strength). Which branch should I make the PR to ?

**Comment by deanilvincent** [comment]
Hello @Ennoriel Apologies for the late response because I was in vacation for the past weeks. Happy New Year to you anyway! 

Great! I saw some new changes and those are amazing. Thanks for contribution!

Regarding the PR, you can target the master branch. :)
