### ISSUE TITLE
index.js:32 Error: Password is empty.

### ISSUE THREAD

**Issue by MedinaGitHub** [deanilvincent/check-password-strength#30]
an error with empty string

![image](https://user-images.githubusercontent.com/16387514/105375728-b9efb700-5be7-11eb-9a7f-3b373fd0a4df.png)

**Comment by deanilvincent** [comment]
Hi @MedinaGitHub ,

Yep, there's a condition in this package that throws Error if the password is empty :) 

https://github.com/deanilvincent/check-password-strength/blob/f08e978d7245e408e1b2ced96b5249bdbecd539f/index.js#L2-L4

I would suggest, for now, is to create an condition that checks if your input password is empty or not. :)

```
if(inputPass){
    console.log(passwordStrength(inputPass).value);
}
```

**Comment by MedinaGitHub** [comment]
yes, maybe it is better to return 0, if not the app crashes.
