### ISSUE TITLE
Is there a reason this does not run in NodeJS ?

### ISSUE THREAD

**Issue by NoSoup4you2** [deanilvincent/check-password-strength#42]
I am wondering if there is a reason why this package does not run not in NodeJs ?
when i install and then run your sample code like
```
const passwordStrength = require('check-password-strength')
console.log(passwordStrength('asdfasdf').value)
```

TypeError: passwordStrength is not a function

**Comment by Ennoriel** [comment]
Hi @NoSoup4you2 ,

There is an issue with the doc. Try the following:

```
const { passwordStrength } = require('check-password-strength')
console.log(passwordStrength('asdfasdf').value)
```

Tell me if that solves your issue.
I will change that in the doc!

**Comment by NoSoup4you2** [comment]
Yes that did the trick...

**Comment by NoSoup4you2** [comment]
After taking a closer look at the code and how you handle special char i think the app code could either benefit from some helper that takes reserved char in regex and translates them into a valid regex var or clarification that the user needs to provide valid regex string for the special char part to work.

**Comment by Ennoriel** [comment]
Hi @NoSoup4you2,

I am not sure to understand what your point is.

```
import cps from 'check-password-strength'
strength = cps.passwordStrength(password, cps.defaultOptions, "/()")
```

The third argument is the special char string allowed. Here the three char "/", "(" and ")" are all allowed.

**Comment by Ennoriel** [comment]
Hello @NoSoup4you2 ,

You are right about that. It does not always is the case, for example `"["` will work but `"[]"` will not as it will be cast as `/[[]]/`. I'll fix it with [this method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#escaping).

Thanks a lot!

**Comment by deanilvincent** [comment]
Hello,

Thanks for submitting an issue/concern. We appreciate it! Known bug fixes are already pushed to `v.2.0.3` :)) Stay safe!

Closing this issue.
