### ISSUE TITLE
Symbol : equal

### ISSUE THREAD

**Issue by nfaugout** [deanilvincent/check-password-strength#53]
Hi,

The equal (=) symbol does not seem to be included in your regexp that checks for symbols.

Is it on purpose ?

If not could you add it ?

Thanks a lot

**Comment by Ennoriel** [comment]
Hi @nfaugout !

Thanks for using the lib and sorry for the late reply.

I think that the allowed symbols have been set without any further reflexion and needs to be think about. You may override it when calling the passwordStrength method with the attribut allowedSymbols:

```
// call signature
const passwordStrength = (password, options = defaultOptions, allowedSymbols="!@#$%^&*")
```

Be aware that at the current moment it may not work with special regexp char ( [ ^. *

I will have a look about it next week :)

Have a nice day!

**Comment by deanilvincent** [comment]
Re-open when necessary, thank you! :)
