### ISSUE TITLE
Some special characters are transformed.

### ISSUE THREAD

**Issue by Ju777** [deanilvincent/check-password-strength#71]
Hello,

thanks for your librairy, it's really nice.

I just noticed that the 3 following characters are "transformed" after a user choose them in his password :

**<** is transformed in **`&lt;`**
**>** is transformed in **`&gt;`**
**&** is transformed in **`&amp;`**

Example : a user chooses the password _`password@444&`_, then the passwordStrength checking actually checks _`password@444&amp;`_. Then, some medium passwords become strong because of length.

What can we do ?

Julien

**Comment by deanilvincent** [comment]
Hi @Ju777 , thank you for your appreciation and feedback. 💯  I'm trying to replicate the issue you mentioned about the "transformed" but I wasn't able to. If it's possible, could you provide an example?  Would it be possible to replicate it on our demo links? Looking forward to your reply.

**Comment by deanilvincent** [comment]
Closing this for now. However, I will re-open this in case there's a follow up information in the future. Thanks
