### ISSUE TITLE
v2.0.9 breaking changes

### ISSUE THREAD

**Issue by dreysolano** [deanilvincent/check-password-strength#77]
I just upgraded from v2.0.7 to v2.0.9, and it appears the changes related to ESM (perhaps?) now cause a critical error on app build.

@deanilvincent @Ennoriel Why were these changes marked as a patch version update and not a major update given the breaking changes?

EDIT: appears that the removal of the default export was perhaps the issue? I see this is identified in the setup docs, but was not called out in the release notes.

**Comment by eaardal** [comment]
Hey I had the same issue but v2.0.10 seems to have resolve it 👍

**Comment by deanilvincent** [comment]
Thank you @eaardal for confirming and using this package. :) Closing this issue now
