### ISSUE TITLE
Wrong default value 

### ISSUE THREAD

**Issue by inzKornel** [deanilvincent/check-password-strength#9]
According to Readme you have wrong default value for password strength. 
Right now it is `{ id: 2, value: 'Weak }`. Should be `Strong`. Add some test to it please :)

**Comment by deanilvincent** [comment]
Oh thanks for your contribution. I appreciate it! :) Bug fixes in version [1.0.8 ](https://www.npmjs.com/package/check-password-strength/v/1.0.8)
